staging-settings:
  user-workflow:
    workflow-name: "stakefit-audit-firewall-staging"
  workflow-artifacts:
    workflow-path: "./workflow.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"

production-settings:
  user-workflow:
    workflow-name: "stakefit-audit-firewall-production"
  workflow-artifacts:
    workflow-path: "./workflow.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"
